### ISSUE TITLE
Big format description is incomplete

### ISSUE THREAD

**Issue by OmniBlade** [OpenSAGE/Docs#1]
Your big format description doesn't note which endian the various integers in the header need to be. You should also note the max path length that is supported for NAME_ENTRY is 260 bytes (The windows max path length) including the null terminated byte as that is all the games allocate space for for the read. See https://github.com/TheAssemblyArmada/Thyme/wiki/BIG-File-Format.

**Comment by feliwir** [comment]
True, i forgot about the byte swapping in the docs. Thanks i'll add that
